-- QualityAgent article quality scores.
-- Stores quality evaluations for both original crawler articles and WriterAgent outputs.

CREATE DATABASE IF NOT EXISTS `research_article_data`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE `research_article_data`;

CREATE TABLE IF NOT EXISTS `article_quality_scores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `source_kind` VARCHAR(32) NOT NULL COMMENT 'original, writer, or writer_plain',
  `source_article_id` BIGINT UNSIGNED NULL COMMENT 'Original crawler article id',
  `candidate_id` BIGINT UNSIGNED NULL COMMENT 'research_article_candidates.id',
  `writer_output_id` BIGINT UNSIGNED NULL COMMENT 'writer_article_outputs.id for generated articles',
  `original_url` VARCHAR(1024) NULL COMMENT 'Original source URL',
  `article_score` DECIMAL(5,2) NULL COMMENT 'Article value score from scoring agent',
  `title` VARCHAR(512) NULL COMMENT 'Scored article title',
  `content_chars` INT UNSIGNED NULL COMMENT 'Scored content character count',
  `word_count` INT UNSIGNED NULL COMMENT 'Scored content word/Chinese character count',
  `if_ai_generated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether the scored text is generated by WriterAgent',
  `quality_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/scored/failed',
  `quality_score` DECIMAL(5,2) NULL COMMENT 'Overall writing quality score',
  `word_count_score` DECIMAL(5,2) NULL COMMENT 'Code-scored word count quality',
  `fluency_score` DECIMAL(5,2) NULL COMMENT 'Language fluency',
  `structure_score` DECIMAL(5,2) NULL COMMENT 'Article structure',
  `attractiveness_score` DECIMAL(5,2) NULL COMMENT 'Title/opening/content attractiveness',
  `ai_feel_score` DECIMAL(5,2) NULL COMMENT 'Low-AI-feel quality score; higher means less AI-like',
  `ai_likelihood_score` DECIMAL(5,2) NULL COMMENT 'AI-likeness score; higher means more AI-like',
  `ai_generated_probability` DECIMAL(5,2) NULL COMMENT 'Probability that a casual reader can spot AI writing',
  `route` VARCHAR(64) NULL COMMENT 'needs_research_writer/manual_review/ready_to_store',
  `rewrite_feedback_prompt` TEXT NULL COMMENT 'Feedback prompt for ResearchAgent/WriterAgent rewrite',
  `quality_payload` JSON NULL COMMENT 'Full QualityAgent JSON payload',
  `quality_model` VARCHAR(100) NULL COMMENT 'LLM model name',
  `quality_version` VARCHAR(50) NULL COMMENT 'Quality scoring version',
  `error_message` TEXT NULL COMMENT 'Quality scoring error if failed',
  `scored_at` DATETIME NULL COMMENT 'When quality scoring succeeded',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quality_source_candidate` (`source_kind`, `candidate_id`),
  KEY `idx_quality_score` (`quality_score`),
  KEY `idx_quality_route` (`route`),
  KEY `idx_quality_status` (`quality_status`),
  KEY `idx_source_article` (`source_article_id`),
  KEY `idx_writer_output` (`writer_output_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='QualityAgent writing quality scores';

-- Typical routing queries:
--
-- Original high-value articles that need rewriting:
-- SELECT candidate_id, title, article_score, quality_score, route
-- FROM article_quality_scores
-- WHERE source_kind = 'original'
--   AND article_score > 75
--   AND quality_score < 70
-- ORDER BY quality_score ASC;
--
-- Writer outputs ready for storage/publishing:
-- SELECT candidate_id, title, quality_score
-- FROM article_quality_scores
-- WHERE source_kind = 'writer'
--   AND quality_score >= 85
-- ORDER BY quality_score DESC;
